export const sculptureList = [
  {
    name: 'Strawberry Stand',
    artist: 'Kiron Roy',
    description: 'An abandoned strawberry stand.',
    url: '/imgs/strawberry.jpg',
    alt: 'An abandoned Strawberry Stand.',
  },
  {
    name: 'Pipes',
    artist: 'Kiron Roy',
    description: ' Pipes for water?',
    url: '/imgs/pipes2.jpg',
    alt: 'Pipes for water',
  },
  {
    name: 'Gas Station',
    artist: 'Kiron Roy',
    description: 'Abandoned gas station.',
    url: '/imgs/gas.jpg',
    alt: 'Abandoned gas station..',
  },
  {
    name: 'Fire',
    artist: 'Kiron Roy',
    description: 'Gallery on fire.',
    url: '/imgs/fire.webp',
    alt: 'Gallery on fire.',
  },
  {
    name: 'Oil',
    artist: 'Kiron Roy',
    description: 'Oil!',
    url: '/imgs/oil.jpg',
    alt: 'An oil rig in a field',
  },
  {
    name: 'Transformer',
    artist: 'Kiron Roy',
    description: 'An electric transformer.',
    url: '/imgs/grid2.jpg',
    alt: 'An electric transformer.',
  },
  {
    name: 'Blimp',
    artist: 'Kiron Roy',
    description: 'Air Blimp.',
    url: '/imgs/blimp.jpg',
    alt: 'Air Blimp.',
  },
  {
    name: 'Home',
    artist: 'Kiron Roy',
    description: ' This is home.',
    url: '/imgs/pole.jpg',
    alt: 'House with a wooden fence.',
  },
  {
    name: 'Crow',
    artist: 'Kiron Roy',
    description: 'Crow on a structure.',
    url: '/imgs/crow.jpg',
    alt: 'Crow on a structure.',
  },
  {
    name: 'Space in between',
    artist: 'Kiron Roy',
    description: 'Space in between two houses.',
    url: '/imgs/space.jpg',
    alt: 'Space in between two houses.',
  },
  {
    name: 'Lamp',
    artist: 'Kiron Roy',
    description: 'A lamp in the window',
    url: '/imgs/lamp.webp',
    alt: 'A lamp in the window.',
  },
  {
    name: 'A/C',
    artist: 'Kiron Roy',
    description: 'Air conditioning unit.',
    url: '/imgs/fan.jpg',
    alt: 'A group of bronze hippo sculptures emerging from the sett sidewalk as if they were swimming.',
  },
  {
    name: 'Binoculars',
    artist: 'Kiron Roy',
    description: 'Look through the binoculars.',
    url: '/imgs/binoculars2.jpg',
    alt: 'A group of bronze hippo sculptures emerging from the sett sidewalk as if they were swimming.',
  },
  {
    name: 'Phone',
    artist: 'Kiron Roy',
    description: 'Answer the phone.',
    url: '/imgs/phone.jpg',
    alt: 'A group of bronze hippo sculptures emerging from the sett sidewalk as if they were swimming.',
  },
  {
    name: 'Key Shop',
    artist: 'Kiron Roy',
    description: 'Local cut keys.',
    url: '/imgs/key.jpg',
    alt: 'A group of bronze hippo sculptures emerging from the sett sidewalk as if they were swimming.',
  },
];
